### ISSUE TITLE
與Delightful的砧板配方衝突，無法獲得至高木樹皮而是普通樹皮

### ISSUE THREAD

**Issue by usoyume** [Minecraft-LightLand/Ars-Nouveau-Flavors-Delight#2]
與Delightful的砧板配方衝突，無法獲得至高木樹皮而是普通樹皮
![706a6854b6ea06a0b340ae54ed7b3ffa_720](https://github.com/user-attachments/assets/54b64dbb-3b65-4712-98f5-9b33911d8e0b)

**Comment by lcy0x1** [comment]
处理好了
